"""initial schema

Revision ID: 1aca3ab81717
Revises: 
Create Date: 2026-09-03 02:52:29.425016
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql
revision: str = '1aca3ab81717'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=True),
    sa.Column('display_name', sa.String(length=120), nullable=True),
    sa.Column('github_login', sa.String(length=120), nullable=True),
    sa.Column('github_access_token', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('github_login')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('projects',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('owner_id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('repository_url', sa.String(length=500), nullable=True),
    sa.Column('settings', sa.JSON().with_variant(postgresql.JSONB(), "postgresql"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('owner_id', 'name', name='uq_project_owner_name')
    )
    op.create_index(op.f('ix_projects_owner_id'), 'projects', ['owner_id'], unique=False)
    op.create_table('ci_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.String(length=32), nullable=False),
    sa.Column('external_id', sa.String(length=200), nullable=False),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('remediation', sa.Text(), nullable=True),
    sa.Column('repository', sa.String(length=300), nullable=True),
    sa.Column('workflow_name', sa.String(length=300), nullable=True),
    sa.Column('workflow_path', sa.String(length=500), nullable=True),
    sa.Column('commit_sha', sa.String(length=64), nullable=True),
    sa.Column('actor', sa.String(length=120), nullable=True),
    sa.Column('html_url', sa.String(length=500), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('evidence', sa.JSON().with_variant(postgresql.JSONB(), "postgresql"), nullable=False),
    sa.Column('details', sa.JSON().with_variant(postgresql.JSONB(), "postgresql"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'external_id', name='uq_ci_event_external')
    )
    op.create_index(op.f('ix_ci_events_occurred_at'), 'ci_events', ['occurred_at'], unique=False)
    op.create_index(op.f('ix_ci_events_project_id'), 'ci_events', ['project_id'], unique=False)
    op.create_index('ix_ci_events_project_occurred', 'ci_events', ['project_id', 'occurred_at'], unique=False)
    op.create_table('scans',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('project_id', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('risk_score', sa.Float(), nullable=True),
    sa.Column('risk_grade', sa.String(length=2), nullable=True),
    sa.Column('package_count', sa.Integer(), nullable=False),
    sa.Column('finding_count', sa.Integer(), nullable=False),
    sa.Column('duration_seconds', sa.Float(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('summary', sa.JSON().with_variant(postgresql.JSONB(), "postgresql"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_scans_project_created', 'scans', ['project_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_scans_project_id'), 'scans', ['project_id'], unique=False)
    op.create_index(op.f('ix_scans_status'), 'scans', ['status'], unique=False)
    op.create_table('dependencies',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('scan_id', sa.String(length=32), nullable=False),
    sa.Column('ecosystem', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=300), nullable=False),
    sa.Column('version', sa.String(length=120), nullable=False),
    sa.Column('depth', sa.Integer(), nullable=False),
    sa.Column('is_direct', sa.Boolean(), nullable=False),
    sa.Column('is_dev', sa.Boolean(), nullable=False),
    sa.Column('manifest_filename', sa.String(length=300), nullable=True),
    sa.Column('parents', sa.JSON().with_variant(postgresql.JSONB(), "postgresql"), nullable=False),
    sa.ForeignKeyConstraint(['scan_id'], ['scans.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('scan_id', 'ecosystem', 'name', 'version', name='uq_dependency_identity')
    )
    op.create_index(op.f('ix_dependencies_scan_id'), 'dependencies', ['scan_id'], unique=False)
    op.create_index('ix_dependencies_scan_name', 'dependencies', ['scan_id', 'name'], unique=False)
    op.create_table('findings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('scan_id', sa.String(length=32), nullable=False),
    sa.Column('category', sa.String(length=32), nullable=False),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('severity_rank', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('detector', sa.String(length=64), nullable=False),
    sa.Column('ecosystem', sa.String(length=32), nullable=True),
    sa.Column('package_name', sa.String(length=300), nullable=True),
    sa.Column('package_version', sa.String(length=120), nullable=True),
    sa.Column('identifier', sa.String(length=120), nullable=True),
    sa.Column('cvss_score', sa.Float(), nullable=True),
    sa.Column('affected_range', sa.String(length=200), nullable=True),
    sa.Column('fixed_version', sa.String(length=120), nullable=True),
    sa.Column('remediation', sa.Text(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('depth', sa.Integer(), nullable=False),
    sa.Column('is_direct', sa.Boolean(), nullable=False),
    sa.Column('risk_contribution', sa.Float(), nullable=False),
    sa.Column('references', sa.JSON().with_variant(postgresql.JSONB(), "postgresql"), nullable=False),
    sa.Column('evidence', sa.JSON().with_variant(postgresql.JSONB(), "postgresql"), nullable=False),
    sa.Column('details', sa.JSON().with_variant(postgresql.JSONB(), "postgresql"), nullable=False),
    sa.ForeignKeyConstraint(['scan_id'], ['scans.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_findings_identifier'), 'findings', ['identifier'], unique=False)
    op.create_index(op.f('ix_findings_package_name'), 'findings', ['package_name'], unique=False)
    op.create_index('ix_findings_scan_category', 'findings', ['scan_id', 'category'], unique=False)
    op.create_index(op.f('ix_findings_scan_id'), 'findings', ['scan_id'], unique=False)
    op.create_index('ix_findings_scan_severity', 'findings', ['scan_id', 'severity'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_findings_scan_severity', table_name='findings')
    op.drop_index(op.f('ix_findings_scan_id'), table_name='findings')
    op.drop_index('ix_findings_scan_category', table_name='findings')
    op.drop_index(op.f('ix_findings_package_name'), table_name='findings')
    op.drop_index(op.f('ix_findings_identifier'), table_name='findings')
    op.drop_table('findings')
    op.drop_index('ix_dependencies_scan_name', table_name='dependencies')
    op.drop_index(op.f('ix_dependencies_scan_id'), table_name='dependencies')
    op.drop_table('dependencies')
    op.drop_index(op.f('ix_scans_status'), table_name='scans')
    op.drop_index(op.f('ix_scans_project_id'), table_name='scans')
    op.drop_index('ix_scans_project_created', table_name='scans')
    op.drop_table('scans')
    op.drop_index('ix_ci_events_project_occurred', table_name='ci_events')
    op.drop_index(op.f('ix_ci_events_project_id'), table_name='ci_events')
    op.drop_index(op.f('ix_ci_events_occurred_at'), table_name='ci_events')
    op.drop_table('ci_events')
    op.drop_index(op.f('ix_projects_owner_id'), table_name='projects')
    op.drop_table('projects')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
